#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-Kakasi
version:      2.00
version_from: Kakasi.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_03
